language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
    - "node_modules"

script:
- npm run build 
- npm run lint
- npm run test

after_success:
  - npm run generate:docs

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local-dir: docs